sudo: required
dist: trusty
language: node_js
node_js:
  - "8"
python:
  - "3.5"
cache:
  - pip
  - yarn
install:
  # Install any dependencies required for building your site here.
  # `awscli` is required for invalidation of CloudFront distributions.
  - pip install awscli
before_script:
  - yarn
script:
  # Build your site (e.g., HTML, CSS, JS) here.
  yarn run build
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: $S3_BUCKET_NAME
    region: $AWS_DEFAULT_REGION
    skip_cleanup: true
    local_dir: dist
    cache_control: "max-age=21600"
    on:
      branch: master
after_deploy:
  - aws configure set preview.cloudfront true
  - test $TRAVIS_BRANCH = "master" && aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
