exclude:		['node_modules', '.sass-cache']

# Dependencies
markdown:         kramdown
highlighter:      rouge
gems: [jekyll-paginate]

# Permalinks
permalink:        pretty

# Setup
title:            '@danielm'
tagline:          'HTML, CSS, and JavaScript developer'
description:      'Notes on modern web development with HTML, CSS, and JavaScript.'
url:              http://danmatthew.co.uk

author:
  name:           'Daniel Matthew'
  url:            https://twitter.com/danielm

paginate:         10

# Custom vars
version:          1.1.1

# Github repositories
github_user: danielmatthew
github_repo_url: https://github.com/danielmatthew/danielmatthew.github.io/

github:
  url:           https://github.com/danielmatthew

twitter:
  url:			https://twitter.com/danielm

treehouse:
  url:			https://teamtreehouse.com/danielmatthew

updated: '06032016'
